### ISSUE TITLE
Question and help

### ISSUE THREAD

**Issue by efernan** [swb1701/RaspberryPi#1]
Hi.
Nice job and good idea!.
I have a SLM-25 sound level meter: https://www.gainexpress.com/products/slm-25
I'm testing your python program soundmeter.py connecting to usb but I can't get it to work, I have the error:

[...]
Traceback (most recent call last):
  File "soundmeter.py", line 21, in <module>
    ret = dev.ctrl_transfer(0xC0,4,0,0,200)
  File "/usr/lib/python2.7/dist-packages/usb/core.py", line 1043, in ctrl_transfer
    self.__get_timeout(timeout))
  File "/usr/lib/python2.7/dist-packages/usb/backend/libusb1.py", line 883, in ctrl_transfer
    timeout))
  File "/usr/lib/python2.7/dist-packages/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 32] Pipe error
[...]

I have changed the idVendor and idProduct variables to the ones I got when executing the lsusb command.

Do you know if my sound level meter would be compatible?
Can you help me?

Thanks in advance.

**Comment by thanasisgnr1** [comment]
I got the same product and I have the same problem because i guess i cant find the proper: dev.ctrl_transfer. You find the solution ?

**Comment by efernan** [comment]
Hi.

I did not find the solution... I'm using the original windows program... :-(

**Comment by thanasisgnr1** [comment]
You mean that you use the program that the decibel meter got (the cd) ?
I want to fit it with the raspberry pi, but i think is difficult.

**Comment by efernan** [comment]
yes, with the CD program... I couldn't get it to work with the raspberry... It's a shame bacause I have to connect it to a laptop every time I want to use it... I can't have it taking data continuously and insert it into influxdb...argg
if you get anything let me know please....
